image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -qq git-ftp 
          - git ftp push --user $FTP_USERNAME –p $FTP_PASSWORD ftp://ftp.unaux.com/htdocs/ 
