image: samueldebruyn/debian-git

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install -qq git-ftp 
          - git ftp push --force --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://ftp.unaux.com/htdocs/ 
